name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          echo "PUBLIC_SUPABASE_URL is: $PUBLIC_SUPABASE_URL"
          npm run build
        env:
          PUBLIC_SUPABASE_URL: "https://aracrovpjnrbpjiqqetb.supabase.co"
          PUBLIC_SUPABASE_PUBLISHABLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyYWNyb3Zwam5yYnBqaXFxZXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ3ODQxMzQsImV4cCI6MjEwMDM2MDEzNH0.gfAaGBXBs0Z1XppnHXPWGa56YHcZ2tjOO53TIkV558Q"
          SUPABASE_SECRET_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyYWNyb3Zwam5yYnBqaXFxZXRiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NDc4NDEzNCwiZXhwIjoyMTAwMzYwMTM0fQ.j3CPe49B0JTMGCaUUukvOOfesn4f6naUwvumaP3TIQE"
          AUTH_SECRET: "1055e0af200d60058782a7018ce2b4b1cc5410d794450e45daa4e24ec480a88"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
